name: CI Pipeline for API & Cucumber Tests

on:
  push:
    branches: [ '**' ]
  pull_request:

permissions:
  contents: write

jobs:
  run-tests:
    name: Run FastAPI & API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install FastAPI dependencies
        working-directory: fastapi-backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server in background
        working-directory: fastapi-backend
        run: |
          nohup uvicorn main:app --host 127.0.0.1 --port 8000 > uvicorn.log 2>&1 &
          sleep 5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Install Allure CLI
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Run API Tests with Maven
        working-directory: api-automation
        run: mvn clean verify

      - name: Verify Allure Results Exist
        working-directory: api-automation
        run: |
          echo "Verifying Allure results..."
          if [ -d "target/allure-results" ] && [ "$(ls -A target/allure-results)" ]; then
            echo "Allure results directory is valid."
          else
            echo "ERROR: Allure results directory is missing or empty."
            exit 1
          fi

      - name: Generate Allure HTML Report
        working-directory: api-automation
        run: |
          allure generate target/allure-results --clean -o target/allure-report
          # Fix absolute paths for GitHub Pages
          find target/allure-report -type f -name '*.html' -exec sed -i 's|href="/|href="./|g; s|src="/|src="./|g' {} +

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: api-automation/target/allure-report

      - name: Upload JaCoCo Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: api-automation/target/site/jacoco

      - name: Publish Allure Report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: api-automation/target/allure-report
