name: CI Pipeline for Cucumber Tests

on:
  push:
    branches: [ '**' ]
  pull_request:

jobs:
  run-tests:
    name: Run API & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Set up Python 3.13
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install FastAPI dependencies
        working-directory: fastapi-backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server in background
        working-directory: fastapi-backend
        run: |
          uvicorn main:app --host 127.0.0.1 --port 8000 &
          sleep 5  # Give server time to start

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Install Allure CLI
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Run Cucumber Tests & Generate Allure Results
        working-directory: api-automation
        run: mvn clean test -Dallure.results.directory=target/allure-results
        continue-on-error: true

      - name: Generate Code Coverage Report
        working-directory: api-automation
        run: mvn verify
        continue-on-error: true

      - name: Generate Allure Report
        working-directory: api-automation
        run: |
          allure generate target/allure-results --clean -o target/allure-report
          find target/allure-report -type f -name '*.html' -exec sed -i 's|href="/|href="./|g; s|src="/|src="./|g' {} +
        continue-on-error: true

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: api-automation/target/allure-report

      - name: Upload JaCoCo Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: api-automation/target/site/jacoco

      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: api-automation/target/allure-report
